/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Automobil;
import domen.Klijent;
import domen.Korisnik;
import domen.ServisnaUsluga;
import domen.ServisniList;
import domen.StavkaServisnogLista;
import domen.VrstaServisneUsluge;
import java.awt.Dimension;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import tablemodel.TableModelAutomobil;
import tablemodel.TableModelServisneUsluge;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;

/**
 *
 * @author Korisnik
 */
public class FrmServisniList extends javax.swing.JFrame {
double iznos;
Klijent nadjen;
boolean popust;
private Korisnik kor;
private Automobil auto;
    /**
     * Creates new form FrmServisniList
     */
    public FrmServisniList() {
        initComponents();
        Dimension d=new Dimension();
        d.setSize(800,1000);
        this.setSize(d); 
        this.setName("Pretraga servisnih listova");
        pack();
        napuniCB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelKlijentInfo = new javax.swing.JLabel();
        jLabelPopust = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldjmbg = new javax.swing.JTextField();
        jButtonPronadjiKlijenta = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxServis = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButtonUbaciUListuStavki = new javax.swing.JButton();
        jTextFieldUkupno = new javax.swing.JTextField();
        jButtonSacuvaj = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldFilter = new javax.swing.JTextField();
        jButtonPronadjiAutomobil = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableAuto = new javax.swing.JTable();
        jButtonIzaberiAutomobil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(null);
        setMinimumSize(null);
        setSize(new java.awt.Dimension(595, 776));

        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Datum servisiranja:");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pretraga klijenata", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(0, 102, 102))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(204, 238, 238));

        jLabelKlijentInfo.setForeground(new java.awt.Color(153, 51, 0));

        jLabelPopust.setForeground(new java.awt.Color(153, 51, 0));

        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Unesi JMBG klijenta:");

        jButtonPronadjiKlijenta.setForeground(new java.awt.Color(0, 102, 102));
        jButtonPronadjiKlijenta.setText("Pronadji klijenta");
        jButtonPronadjiKlijenta.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 102)));
        jButtonPronadjiKlijenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPronadjiKlijentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldjmbg, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonPronadjiKlijenta, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelKlijentInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(jLabelPopust, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(160, 160, 160))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldjmbg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPronadjiKlijenta, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelKlijentInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jLabelPopust, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Unos stavki", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(0, 102, 102))); // NOI18N

        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Izaberi Servis:");

        jComboBoxServis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxServisActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jList1);

        jButtonUbaciUListuStavki.setForeground(new java.awt.Color(0, 102, 102));
        jButtonUbaciUListuStavki.setText("Ubaci u listu stavki");
        jButtonUbaciUListuStavki.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 102)));
        jButtonUbaciUListuStavki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUbaciUListuStavkiActionPerformed(evt);
            }
        });

        jButtonSacuvaj.setForeground(new java.awt.Color(0, 102, 102));
        jButtonSacuvaj.setText("Sacuvaj servisni list");
        jButtonSacuvaj.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 102)));
        jButtonSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSacuvajActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Ukupan iznos:");

        jPanel5.setBackground(new java.awt.Color(226, 243, 243));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxServis, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonUbaciUListuStavki, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldUkupno, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(67, 67, 67))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxServis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jButtonUbaciUListuStavki, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldUkupno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jXDatePicker1.setFormats(new SimpleDateFormat("yyyy-MM-dd"));

        jButton1.setForeground(new java.awt.Color(0, 102, 102));
        jButton1.setText("Prikazi izvestaj");
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 102)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pretraga automobila", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(0, 102, 102))); // NOI18N

        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Filter(registarska oznaka):");

        jButtonPronadjiAutomobil.setForeground(new java.awt.Color(0, 102, 102));
        jButtonPronadjiAutomobil.setText("Pronadji automobil");
        jButtonPronadjiAutomobil.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 102)));
        jButtonPronadjiAutomobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPronadjiAutomobilActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(226, 243, 243));

        jTableAuto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTableAuto);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButtonIzaberiAutomobil.setForeground(new java.awt.Color(0, 102, 102));
        jButtonIzaberiAutomobil.setText("Izaberi automobil");
        jButtonIzaberiAutomobil.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 102)));
        jButtonIzaberiAutomobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIzaberiAutomobilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(26, 26, 26)
                        .addComponent(jTextFieldFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonPronadjiAutomobil, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addComponent(jButtonIzaberiAutomobil, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPronadjiAutomobil, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonIzaberiAutomobil, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(218, 218, 218)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPronadjiKlijentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPronadjiKlijentaActionPerformed
       
        
        
        String jmbg=jTextFieldjmbg.getText().trim();
        if(jmbg.isEmpty()){
            JOptionPane.showMessageDialog(this,"Niste popunili polje za pretragu.","verifikacija", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Klijent klijent= new Klijent();
        klijent.setJmbg(jmbg);
        KlijentskiZahtev zahtev= new  KlijentskiZahtev();
        zahtev.setParametar(klijent);
        zahtev.setOperacija(operacije.Operacija.NADJI_KLIJENTA);
        komunikacija.Komunikacija.getInstance().posaljiZahtev(zahtev);
        ServerskiOdgovor odgovor= komunikacija.Komunikacija.getInstance().primiOdgovor();
        
        if(odgovor.getIzuzetak()==null){
        nadjen = (Klijent) odgovor.getParametar();
        jLabelKlijentInfo.setText("Ime: "+nadjen.getIme()+",Prezime: "+nadjen.getPrezime());
        JOptionPane.showMessageDialog(this,odgovor.getPoruka(),"Uspeh",JOptionPane.PLAIN_MESSAGE);
        }else {
        JOptionPane.showMessageDialog(this,odgovor.getPoruka(),"Greska",JOptionPane.ERROR_MESSAGE);
        return;
        }
       
        
        zahtev.setOperacija(operacije.Operacija.NADJI_SERVISNE_LISTOVE);
        ServisniList sl= new ServisniList();
        sl.setKlijent(klijent);
        zahtev.setParametar(sl);
        komunikacija.Komunikacija.getInstance().posaljiZahtev(zahtev);
        odgovor= komunikacija.Komunikacija.getInstance().primiOdgovor();
        ArrayList<ServisniList>listasl=(ArrayList<ServisniList>) odgovor.getParametar();
        if( listasl.size()>3){
        popust=true;
        jLabelPopust.setText("Klijent ima prava na 10% popusta.");
            System.out.println("popust");
        }
    }//GEN-LAST:event_jButtonPronadjiKlijentaActionPerformed

    private void jComboBoxServisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxServisActionPerformed
       VrstaServisneUsluge vsu= (VrstaServisneUsluge) jComboBoxServis.getModel().getSelectedItem();
       KlijentskiZahtev zahtev= new  KlijentskiZahtev();
       ServisnaUsluga su= new ServisnaUsluga();
       su.setVrstaServisneUsluge(vsu);
       zahtev.setParametar(su);
       zahtev.setOperacija(operacije.Operacija.NADJI_SERVISNE_USLUGE_IZ_VRSTE);
       komunikacija.Komunikacija.getInstance().posaljiZahtev(zahtev);
       ServerskiOdgovor odgovor= komunikacija.Komunikacija.getInstance().primiOdgovor();
       if(odgovor.getIzuzetak()==null){
        JOptionPane.showMessageDialog(this,odgovor.getPoruka(),"Uspeh",JOptionPane.PLAIN_MESSAGE);
        }else{
        JOptionPane.showMessageDialog(this,odgovor.getPoruka(),"Greska",JOptionPane.ERROR_MESSAGE);
        } 
       
       ArrayList <ServisnaUsluga> lista = (ArrayList <ServisnaUsluga>) odgovor.getParametar();
       
       DefaultListModel model = new DefaultListModel();
       model.removeAllElements();
       
       for (ServisnaUsluga servusl : lista) {
            model.addElement(servusl);
       }
       
       jList1.setModel(model);
    }//GEN-LAST:event_jComboBoxServisActionPerformed

    private void jButtonUbaciUListuStavkiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUbaciUListuStavkiActionPerformed
        List pomocna = jList1.getSelectedValuesList();
        if(pomocna.isEmpty()){
        JOptionPane.showMessageDialog(this, "Niste izabrali servisnu uslugu");
        return;
        }
        TableModelServisneUsluge model= (TableModelServisneUsluge) jTable1.getModel();
       
        //da li vec postoji u listi
        ArrayList<ServisnaUsluga> listaPostojecih = model.vratilistu();
        for (Object object : pomocna) {
            ServisnaUsluga usluga= (ServisnaUsluga) object;
            String poruka=""; 
            for (ServisnaUsluga su : listaPostojecih) {
            if(usluga.getNazivServisneUsluge().equals(su.getNazivServisneUsluge())){
            poruka+="Vec ste uneli servisnu uslugu "+usluga.getNazivServisneUsluge()+"\n";
            }
            }
            if(!poruka.isEmpty()){
            JOptionPane.showMessageDialog(this, poruka);
            return;
            }
            model.ubaciUListu(usluga);
            iznos+=usluga.getCena()*usluga.getVremeTrajanja();
        }
        jTextFieldUkupno.removeAll();
        if(popust){
        iznos-=iznos*0.1;    
        jTextFieldUkupno.setText(iznos+" ");                                     //proveri ovo
        }else{
        jTextFieldUkupno.setText(iznos+" ");
        }
      
    }//GEN-LAST:event_jButtonUbaciUListuStavkiActionPerformed

    private void jButtonSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSacuvajActionPerformed
    String poruka="";
    Date datum=jXDatePicker1.getDate();
    if(datum ==null){
    poruka+="Niste izabrali datum. \n";
    }
    TableModelServisneUsluge model= (TableModelServisneUsluge) jTable1.getModel();
    ArrayList<ServisnaUsluga> listausluga= model.vratilistu();
    ArrayList<StavkaServisnogLista> listastavki=new ArrayList<>();
    int rb=1;
        for (ServisnaUsluga usluga : listausluga) {
            StavkaServisnogLista stavka= new StavkaServisnogLista(null,rb, usluga.getCena()*usluga.getVremeTrajanja(), usluga);
            rb++;
            listastavki.add(stavka);
        }
    if(listastavki.isEmpty()){
    poruka+="Niste izabrali nijednu stavku servisnog lista. \n";
    }    
    if(!poruka.isEmpty()){
    JOptionPane.showMessageDialog(this, poruka);
    return;
    }
       
       ServisniList list= new ServisniList(-1, datum, iznos, nadjen, listastavki,kor,auto);
       KlijentskiZahtev zahtev= new  KlijentskiZahtev();
       zahtev.setParametar(list);
       zahtev.setOperacija(operacije.Operacija.ZAPAMTI_SERVISNI_LIST);
       komunikacija.Komunikacija.getInstance().posaljiZahtev(zahtev);
       ServerskiOdgovor odgovor= komunikacija.Komunikacija.getInstance().primiOdgovor();
       if(odgovor.getIzuzetak()==null){
        JOptionPane.showMessageDialog(this,odgovor.getPoruka(),"Uspeh",JOptionPane.PLAIN_MESSAGE);
        }else{
        JOptionPane.showMessageDialog(this,odgovor.getPoruka(),"Greska",JOptionPane.ERROR_MESSAGE);
        } 
      
    }//GEN-LAST:event_jButtonSacuvajActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FrmIzvestaj frm= new FrmIzvestaj(this, true);
        frm.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonPronadjiAutomobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPronadjiAutomobilActionPerformed
        String filter=jTextFieldFilter.getText().toUpperCase();
        if(filter.isEmpty()){
        JOptionPane.showMessageDialog(this,"Niste popunili polje za pretragu.","verifikacija", JOptionPane.ERROR_MESSAGE);
        return;
        }
        Automobil a= new Automobil();
        a.setRegistarskiBroj(filter);
       KlijentskiZahtev zahtev= new  KlijentskiZahtev();
       zahtev.setParametar(a);
       zahtev.setOperacija(operacije.Operacija.VRATI_LISTU_AUTOMOBILA);
       komunikacija.Komunikacija.getInstance().posaljiZahtev(zahtev);
       ServerskiOdgovor odgovor= komunikacija.Komunikacija.getInstance().primiOdgovor();
       if(odgovor.getIzuzetak()==null){
        JOptionPane.showMessageDialog(this,odgovor.getPoruka(),"Uspeh",JOptionPane.PLAIN_MESSAGE);
        }else{
        JOptionPane.showMessageDialog(this,odgovor.getPoruka(),"Greska",JOptionPane.ERROR_MESSAGE);
        } 
       
       ArrayList<Automobil>lista= (ArrayList<Automobil>) odgovor.getParametar();
       TableModelAutomobil model= (TableModelAutomobil) jTableAuto.getModel();
       model.setLista(lista);
    }//GEN-LAST:event_jButtonPronadjiAutomobilActionPerformed

    private void jButtonIzaberiAutomobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIzaberiAutomobilActionPerformed
        int indeex=jTableAuto.getSelectedRow();
        if(indeex==-1){
        JOptionPane.showMessageDialog(this, "Niste izabrali automobil.");
        return;
        }
        TableModelAutomobil model= (TableModelAutomobil) jTableAuto.getModel();
        auto=model.getAuto(indeex);
    }//GEN-LAST:event_jButtonIzaberiAutomobilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmServisniList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmServisniList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmServisniList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmServisniList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmServisniList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonIzaberiAutomobil;
    private javax.swing.JButton jButtonPronadjiAutomobil;
    private javax.swing.JButton jButtonPronadjiKlijenta;
    private javax.swing.JButton jButtonSacuvaj;
    private javax.swing.JButton jButtonUbaciUListuStavki;
    private javax.swing.JComboBox jComboBoxServis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelKlijentInfo;
    private javax.swing.JLabel jLabelPopust;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableAuto;
    private javax.swing.JTextField jTextFieldFilter;
    private javax.swing.JTextField jTextFieldUkupno;
    private javax.swing.JTextField jTextFieldjmbg;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    // End of variables declaration//GEN-END:variables

    private void napuniCB() {
       KlijentskiZahtev zahtev= new  KlijentskiZahtev();
        zahtev.setOperacija(operacije.Operacija.VRATI_LISTU_VRSTA_SERVISNIH_USLUGA);
        komunikacija.Komunikacija.getInstance().posaljiZahtev(zahtev);
        ServerskiOdgovor odgovor= komunikacija.Komunikacija.getInstance().primiOdgovor();
        ArrayList <VrstaServisneUsluge> lista = (ArrayList <VrstaServisneUsluge>) odgovor.getParametar();
        for (VrstaServisneUsluge vsu : lista) {
            jComboBoxServis.addItem(vsu);
        }
        TableModelServisneUsluge model= new TableModelServisneUsluge(new ArrayList<>());
        jTable1.setModel(model);
        TableModelAutomobil amodel= new TableModelAutomobil(new ArrayList<>());
        jTableAuto.setModel(amodel);
    }

    

    public void setKor(Korisnik kor) {
        this.kor = kor;
    }

   

    
}
